

export const GET_SINGLPACH_DATA = "GET_SINGLPACH_DATA";
export const GET_SINGLPACH_SUCCESS = "GET_SINGLPACH_SUCCESS";
export const GET_SINGLPACH_FAILURE = "GET_SINGLPACH_FAILURE";

export const OPEN_MODAL_EDIT = "OPEN_MODAL_EDIT";

export const UPDATE_SINGLPACH_REQUEST = "UPDATE_SINGLPACH_REQUEST";
export const UPDATE_SINGLPACH_SUCCESS = "UPDATE_SINGLPACH_SUCCESS"
export const UPDATE_SINGLPACH_FAILURE = "UPDATE_SINGLPACH_FAILURE";

export const OPEN_MODAL_COMPONENT = "OPEN_MODAL_COMPONENT";
export const CLOSS_MODAL_COMPONENT = "CLOSS_MODAL_COMPONENT";

export const DELETE_SINGLPACH_REQUEST = "DELETE_SINGLPACH_REQUEST";
export const DELETE_SINGLPACH_SUCCESS = "DELETE_SINGLPACH_SUCCESS"
export const DELETE_SINGLPACH_FAILURE = "DELETE_SINGLPACH_FAILURE";