


export const UPDATE_TODOITEM_REQUEST = "UPDATE_TODOITEM_REQUEST";
export const UPDATE_TODOITEM_SUCCESS = "UPDATE_TODOITEM_SUCCESS"
export const UPDATE_TODOITEM_FAILURE = "UPDATE_TODOITEM_FAILURE";

export const GET_TODO_ITEMS_REQUEST = "GET_TODO_ITEMS_REQUEST";
export const GET_TODO_ITEMS_SUCCESS = "GET_TODO_ITEMS_SUCCESS";
export const GET_TODO_ITEMS_FAILURE = "GET_TODO_ITEMS_FAILURE";



export const ADD_TODOITEM_REQUEST ="ADD_TODOITEM_REQUEST";
export const ADD_TODOITEM_SUCCESS ="ADD_TODOITEM_SUCCESS";
export const ADD_TODOITEM_FAILURE ="ADD_TODOITEM_FAILURE";


export const DELETE_ALL_TODO_REQUEST = "DELETE_ALL_TODO_REQUEST";
export const DELETE_ALL_TODO_SUCCESS = "DELETE_ALL_TODO_SUCCESS";
export const DELETE_ALL_TODO_FAILURE = "DELETE_ALL_TODO_FAILURE";

export const DELETE_SINGLPACH_REQUEST = "DELETE_SINGLPACH_REQUEST";
export const DELETE_SINGLPACH_SUCCESS = "DELETE_SINGLPACH_SUCCESS";
export const DELETE_SINGLPACH_FAILURE = "DELETE_SINGLPACH_FAILURE";


export const GET_SINGLPACH_DATA = "GET_SINGLPACH_DATA";
export const GET_SINGLPACH_SUCCESS = "GET_SINGLPACH_SUCCESS";
export const GET_SINGLPACH_FAILURE = "GET_SINGLPACH_FAILURE";