

export const CHANGE_CONTACT_FORM = "CHANGE_CONTACT_FORM";


export const CONTACT_FORM_REQVEST = "CONTACT_FORM_REQVEST";
export const CONTACT_FORM_SUCCESS = "CONTACT_FORM_SUCCESS";
export const CONTACT_FORM_FAILURE = "CONTACT_FORM_FAILURE";

